import type { StreamListItem } from "../entities/stream/model/stream.ts";

export const STREAMS_PER_PAGE = 6;

export function buildMockStreams(): StreamListItem[] {
  return [
    createStream({
      availableActions: ["unpublish", "edit", "view"],
      createdAt: "2024-05-12T08:42:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=640&q=80",
      position: 1,
      status: "active",
      streamId: "stream-morning-light",
      summary: "Warm acoustic sounds and reflective folk favorites to start your day with clarity and calm.",
      title: "Morning Light Radio",
    }),
    createStream({
      availableActions: ["unpublish", "edit", "view"],
      createdAt: "2024-05-11T09:15:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=640&q=80",
      position: 2,
      status: "active",
      streamId: "stream-urban-pulse",
      summary: "Hip hop, R&B, and neon-lit late city energy curated for high-tempo daytime rotation.",
      title: "Urban Pulse",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-14T07:20:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=640&q=80",
      position: 3,
      status: "draft",
      streamId: "stream-coastal-drive",
      summary: "Chill electronic textures with a slow-sunset pace and soft west-coast motion.",
      title: "Coastal Drive",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-09T18:05:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=640&q=80",
      position: 4,
      status: "inactive",
      streamId: "stream-jazz-lounge",
      summary: "Classic lounge standards and intimate jazz recordings for late-evening listening.",
      title: "Jazz Lounge",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-15T06:55:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=640&q=80",
      position: 5,
      status: "draft",
      streamId: "stream-deep-focus",
      summary: "Ambient and instrumental programming built for focus sessions, study blocks, and quiet work.",
      title: "Deep Focus",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-08T19:00:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=640&q=80",
      position: 6,
      status: "inactive",
      streamId: "stream-game-day-central",
      summary: "Sports talk, matchday buildup, and reaction segments anchored around major live events.",
      title: "Game Day Central",
    }),
    createStream({
      availableActions: ["unpublish", "edit", "view"],
      createdAt: "2024-05-07T12:30:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=640&q=80",
      position: 7,
      status: "active",
      streamId: "stream-sunset-sessions",
      summary: "Golden-hour indie grooves, relaxed guitar lines, and low-pressure transitions.",
      title: "Sunset Sessions",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-06T10:00:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=640&q=80",
      position: 8,
      status: "inactive",
      streamId: "stream-night-frequencies",
      summary: "Midnight electronica and club-leaning sets for late listening blocks.",
      title: "Night Frequencies",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-05T16:00:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=640&q=80",
      position: 9,
      status: "draft",
      streamId: "stream-quiet-harbor",
      summary: "Soft piano, strings, and restful arrangements intended for downtime.",
      title: "Quiet Harbor",
    }),
    createStream({
      availableActions: ["unpublish", "edit", "view"],
      createdAt: "2024-05-04T08:20:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=640&q=80",
      position: 10,
      status: "active",
      streamId: "stream-studio-select",
      summary: "Fresh playlist rotation driven by weekly editorial picks across emerging genres.",
      title: "Studio Select",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-03T14:10:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=640&q=80",
      position: 11,
      status: "inactive",
      streamId: "stream-vinyl-cabinet",
      summary: "Archive soul, funk, and warm analog recordings from the station library.",
      title: "Vinyl Cabinet",
    }),
    createStream({
      availableActions: ["publish", "edit", "view"],
      createdAt: "2024-05-02T21:00:00.000Z",
      imageUrl: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=640&q=80",
      position: 12,
      status: "draft",
      streamId: "stream-atlas-fm",
      summary: "Cross-region curation with travel stories, field recordings, and global pop selections.",
      title: "Atlas FM",
    }),
  ];
}

function createStream(stream: StreamListItem): StreamListItem {
  return stream;
}
